### ISSUE TITLE
[Frontend]: Update HomePage after login 

### ISSUE THREAD

**Issue by aClassCodeBreaker** [VirittamoHelsinki/saukko-app#103]
### Prerequisites

- [X] I have read the [Git Etiquette](https://github.com/LeDuble/Git-Etiquette). (Required)
- [X] I agree to follow the [Code of Conduct](). (Required)
- [ ] Are you intending to include tests? (Optional)

### Summary (Required)

Käyttäjänä haluan saada tiedon, että lähettämäni tiedot odottavat vahvistusta / hyväksymistä
- [ ] Järjestelmään tallentuu tieto, että opettajalta odotetaan asiakkaan lähettämien tietojen hyväksymistä 

### Potential Solution (Required)

- [ ] If pending flag has been raised in backend signifying that the customer doesn't yet have the  permission to continue using the application, this infopage appear

### In which category does the issue belong? (Required)

Documentation 📝 - Changes to the documentation.

**Comment by Mirazum** [comment]
done
