### ISSUE TITLE
[Frontend]: Add company name

### ISSUE THREAD

**Issue by aClassCodeBreaker** [VirittamoHelsinki/saukko-app#161]
### Prerequisites

- [X] I have read the [Git Etiquette](https://github.com/LeDuble/Git-Etiquette). (Required)
- [X] I agree to follow the [Code of Conduct](). (Required)
- [ ] Are you intending to include tests? (Optional)

### Summary 

As an administrator, I want to be able to add the  company info so that I can create a new company instance

 type in BusinessID to fetch data from API
Company name edit field appears

### In which category does the issue belong? 
#161

Documentation 📝 - Changes to the documentation.

**Comment by Mirazum** [comment]
done
