### ISSUE TITLE
[Frontend]: Compose the select degree page for  company 

### ISSUE THREAD

**Issue by aClassCodeBreaker** [VirittamoHelsinki/saukko-app#164]
### Prerequisites

- [X] I have read the [Git Etiquette](https://github.com/LeDuble/Git-Etiquette). (Required)
- [X] I agree to follow the [Code of Conduct](). (Required)
- [ ] Are you intending to include tests? (Optional)

### Summary (Required)

As an administrator, I want to select a degree from the ePerusteet list so that I can assign it to a given company
- [ ] The colour of a single data item in the list changes between light yellow  and light blue
- [ ] Use the same, existing Saukko-DB key-values pairs 

### Potential Solution (Required)

- [ ]

### In which category does the issue belong? (Required)

Documentation 📝 - Changes to the documentation.

**Comment by Mirazum** [comment]
done
