### ISSUE TITLE
[Frontend]: Login update

### ISSUE THREAD

**Issue by aClassCodeBreaker** [VirittamoHelsinki/saukko-app#185]
### Prerequisites

- [X] I have read the [Git Etiquette](https://github.com/LeDuble/Git-Etiquette). (Required)
- [X] I agree to follow the [Code of Conduct](). (Required)
- [ ] Are you intending to include tests? (Optional)

### Summary (Required)

Update login functionality according to updated plan.
- [ ] Remove add account from login page
- [ ] Right after login the user is directed to his/her landing page according to the role
- [ ] Colors in login sequence are the same for all roles.
- [ ] The individual colors will appear only after the user have been forwarded to his/her landing page

Note
- [ ] Registration info will be written temporarily during the printing sequence -> the forms will be re-used later

### Potential Solution (Required)

- [ ]

### In which category does the issue belong? (Required)

Documentation 📝 - Changes to the documentation.

**Comment by Mirazum** [comment]
done
