### ISSUE TITLE
[Frontend]: Ensure that the data is in an acceptable format before storing it in the database - estimation: 1

### ISSUE THREAD

**Issue by aClassCodeBreaker** [VirittamoHelsinki/saukko-app#294]
### Prerequisites

- [X] I have read the [Git Etiquette](https://github.com/LeDuble/Git-Etiquette). (Required)
- [X] I agree to follow the [Code of Conduct](). (Required)
- [ ] Are you intending to include tests? (Optional)

### Summary (Required)

As a frontend security officer, I want to make sure that the data entered into the forms or data fields is in the correct format

Acceptance criteria
- [ ] The format of the input data has been checked

### Potential Solution (Required)

- [ ]

### In which category does the issue belong? (Required)

Documentation 📝 - Changes to the documentation.

**Comment by Mirazum** [comment]
done
