### ISSUE TITLE
[Frontend]: Update - swapping radio button headers - estimation: 1

### ISSUE THREAD

**Issue by aClassCodeBreaker** [VirittamoHelsinki/saukko-app#299]
### Prerequisites

- [X] I have read the [Git Etiquette](https://github.com/LeDuble/Git-Etiquette). (Required)
- [X] I agree to follow the [Code of Conduct](). (Required)
- [ ] Are you intending to include tests? (Optional)

### Summary (Required)

On the "Suoritukset ja tehtävät" page, the headings "osaa itsenäisesti" and "osaa ohjatusti" radio buttons should be reversed so that "osaa ohjatusti" is on the left.

Acceptance criteria
- [ ] When the change has been done and updated

### Potential Solution (Required)

- [ ]

### In which category does the issue belong? (Required)

Documentation 📝 - Changes to the documentation.

**Comment by Mirazum** [comment]
done
