### ISSUE TITLE
[Frontend]: Salasanan palauttaminen

### ISSUE THREAD

**Issue by aClassCodeBreaker** [VirittamoHelsinki/saukko-app#44]
### Prerequisites

- [X] I have read the [Git Etiquette](https://github.com/LeDuble/Git-Etiquette). (Required)
- [X] I agree to follow the [Code of Conduct](). (Required)
- [ ] Are you intending to include tests? (Optional)

### Summary (Required)

Käyttäjänä haluan antaa sähköpostiosoitteeni lomakkeelle, jotta voin palauttaa salasanani

- [ ] Sisäänkirjautumissivulla oleva linkki ohjaa sähköpostiosoitteen palautuslomakkeelle
- [ ] Sähköpostiosoitteen syöttömahdollisuus 
- [ ] Lähetä-painiketta painamalla lähetetään annettuun sähköpostiin linkki
- [ ] Käyttäjä saa tiedon linkin lähetettämisestä

### Potential Solution (Required)

- [ ] 

### In which category does the issue belong? (Required)

Documentation 📝 - Changes to the documentation.

**Comment by Mirazum** [comment]
done
