### ISSUE TITLE
[Frontend]: NotificationBadge

### ISSUE THREAD

**Issue by aClassCodeBreaker** [VirittamoHelsinki/saukko-app#72]
### Prerequisites

- [X] I have read the [Git Etiquette](https://github.com/LeDuble/Git-Etiquette). (Required)
- [X] I agree to follow the [Code of Conduct](). (Required)
- [ ] Are you intending to include tests? (Optional)

### Summary (Required)

Asiakaskäyttäjänä haluan nähdä pääsivulla kaikki ilmoitukset, jotta pystyn helposti hahmottamaan miten osaamisen tunnistamisen prosessi etenee. 

- [ ] Ilmoitukset osion tiedot päivittyvät automaattisesti, kun tehtäviini liittyviä suorituksia on hyväksytty tai jos olen saanut tehtäviin liittyviä viestejä 
- [ ] Vastatut viestit ja kommentoidut tehtävät poistuvat ilmoitukset-laskureista 

### Potential Solution (Required)

- [ ] Dynamic number, 
- [ ] text, 
- [ ] color. 
- [ ] Static icon.

Used in home page for all 3 roles.
Klikattava komponentti!

### In which category does the issue belong? (Required)

Documentation 📝 - Changes to the documentation.

**Comment by Mirazum** [comment]
done
