### ISSUE TITLE
[Frontend]: MessagePreview

### ISSUE THREAD

**Issue by aClassCodeBreaker** [VirittamoHelsinki/saukko-app#86]
### Prerequisites

- [X] I have read the [Git Etiquette](https://github.com/LeDuble/Git-Etiquette). (Required)
- [X] I agree to follow the [Code of Conduct](). (Required)
- [ ] Are you intending to include tests? (Optional)

### Summary (Required)

Käyttäjänä haluan nähdä ilmoitukset sivulla viestit, jotta pystyn käymään keskustelua tutkinnon osaan liittyen.

- [ ] Props: senders name + role, subtitle (vastasi kysymykseen), unit, date and time, color, icon, link. 
Static: Arrow

- [ ] Used in notifcations page for all 3 roles.

### Potential Solution (Required)

- [ ] 

### In which category does the issue belong? (Required)

Documentation 📝 - Changes to the documentation.

**Comment by Mirazum** [comment]
done
