### ISSUE TITLE
[Frontend]: Alapalkki-komponentti

### ISSUE THREAD

**Issue by aClassCodeBreaker** [VirittamoHelsinki/saukko-app#91]
### Prerequisites

- [X] I have read the [Git Etiquette](https://github.com/LeDuble/Git-Etiquette). (Required)
- [X] I agree to follow the [Code of Conduct](). (Required)
- [ ] Are you intending to include tests? (Optional)

### Summary (Required)

Asiakaskäyttäjänä haluan navigoida alapalkin kautta sovelluksen etusivulle, katsoa omia suorituksiani tai tarkastella oman profiilisivuni tietoja (User story 3)
- [ ]

### Potential Solution (Required)

- [ ] Updating UserNav component to have 3-4 icons, color and link as props.

### In which category does the issue belong? (Required)

Documentation 📝 - Changes to the documentation.

**Comment by estherguilland** [comment]
Updating UserNav component to have 3-4 icons, color and link as props.
